"""Tests for the promote (draft -> suite cleanup) and discover (project target scan) helpers."""
import ast

from scripts.adapters import python_pytest
from scripts.core import discover, promote

_DRAFT = '''"""Generated by AI Test Pilot — REVIEW before promoting.
Tests are proposed, never auto-committed.
"""
import sys

import pytest

sys.path.insert(0, '/some/project/root')

from scripts.quality.diversity import distinct_n, vocabulary_size


def test_distinct_n_all_unique():
    """All-distinct bigrams."""
    result = distinct_n(texts=['a b', 'c d'], n=2)
    assert repr(result) == '1.0', 'proportion of unique bigrams'


def test_vocabulary_size_basic():
    result = vocabulary_size(texts=['x y'])
    assert repr(result) == '2'
'''


# ── promote: standalone cleanup ──────────────────────────────────────────────
def test_cleaned_source_strips_boilerplate_and_rewrites_locks():
    out = promote.cleaned_source(_DRAFT)
    assert "import sys" not in out
    assert "sys.path.insert" not in out
    assert "Generated by AI Test Pilot" not in out
    assert "repr(result)" not in out
    # repr-lock became a real value assertion (message dropped)
    assert "assert result == 1.0" in out
    assert "assert result == 2" in out
    # the target import survives
    assert "from scripts.quality.diversity import" in out
    # output is valid Python
    ast.parse(out)


def test_cleaned_source_unused_pytest_import_removed():
    assert "import pytest" not in promote.cleaned_source(_DRAFT)


def test_approx_wraps_floats_and_keeps_pytest():
    out = promote.cleaned_source(_DRAFT, approx=True)
    assert "pytest.approx(1.0)" in out
    assert "import pytest" in out
    # an int-valued lock is left exact (no float -> no approx)
    assert "assert result == 2" in out


def test_non_repr_assert_is_left_untouched():
    src = "def test_x():\n    result = 1\n    assert result > 0\n"
    assert "assert result > 0" in promote.cleaned_source(src)


# ── promote: append into an existing suite ───────────────────────────────────
def test_promote_into_dedups_and_merges_imports(tmp_path):
    suite = tmp_path / "test_diversity.py"
    suite.write_text(
        "from scripts.quality.diversity import distinct_n\n\n\n"
        "def test_vocabulary_size_basic():\n    pass\n",
        encoding="utf-8",
    )
    summary = promote.promote_into(_DRAFT, suite)

    assert summary["added"] == ["test_distinct_n_all_unique"]          # the new one
    assert summary["skipped_duplicates"] == ["test_vocabulary_size_basic"]
    assert "scripts.quality.diversity" in summary["imports_merged"]

    text = suite.read_text(encoding="utf-8")
    ast.parse(text)                                                    # still valid
    # import line now carries both names, on one line
    assert "from scripts.quality.diversity import distinct_n, vocabulary_size" in text
    # the duplicate was NOT appended a second time
    assert text.count("def test_vocabulary_size_basic") == 1
    assert "def test_distinct_n_all_unique" in text


# ── discover: project scan + bucketing ───────────────────────────────────────
def test_discover_buckets_testable_vs_complex(tmp_path):
    proj = tmp_path / "demo-project"
    scripts = proj / "scripts"
    scripts.mkdir(parents=True)
    (scripts / "mod.py").write_text(
        "from typing import Callable\n\n"
        "def simple(a: int, b: str) -> int:\n    return a\n\n"
        "def with_callable(fn: Callable[[dict], str]):\n    return fn\n\n"
        "def _private(x):\n    return x\n",
        encoding="utf-8",
    )
    reports = discover.discover(proj, python_pytest)
    by_rel = {r.rel: r for r in reports}
    rep = by_rel["scripts/mod.py"]

    assert rep.testable == ["simple"]                 # private excluded, complex excluded
    assert [name for name, _ in rep.needs_fixtures] == ["with_callable"]
    assert rep.target_path(proj) == "../demo-project/scripts/mod.py"


def test_discover_skips_plumbing_and_empty_modules(tmp_path):
    proj = tmp_path / "p"
    scripts = proj / "scripts"
    scripts.mkdir(parents=True)
    (scripts / "logger.py").write_text("def get_logger():\n    return None\n", encoding="utf-8")
    (scripts / "constants.py").write_text("X = 1\n", encoding="utf-8")  # no functions
    assert discover.discover(proj, python_pytest) == []
