"""Promote a generated draft test file into clean, suite-ready form.

Fully deterministic (no LLM, zero tokens — top rung of the efficiency ladder). It does
the mechanical cleanup a human otherwise does by hand before committing a draft:

1. strips the generated boilerplate header + the `import sys` / `sys.path.insert(...)`
   bootstrap (the target project's own pytest config resolves imports);
2. rewrites golden `assert repr(result) == '<literal>'[, msg]` locks into real value
   assertions `assert result == <value>` (optionally `pytest.approx(...)` for floats);
3. with `--into <suite>`, appends ONLY the non-duplicate test functions into an existing
   suite file and merges the import line — leaving the rest of that file untouched.

The draft files themselves are never mutated; promote reads them and writes elsewhere.
"""
from __future__ import annotations

import ast
from pathlib import Path


# ── assertion rewriting ──────────────────────────────────────────────────────
def _rewrite_assert(node: ast.Assert, *, approx: bool) -> tuple[ast.Assert, bool]:
    """`assert repr(X) == '<literal>'[, msg]` -> `assert X == <value>`.

    Returns (node, used_pytest). Any assert that is not a repr-lock passes through
    unchanged. If the locked string is not a parseable literal (e.g. a default
    `<object at 0x..>` repr), the assert is left as-is — there is nothing safe to rewrite.
    """
    t = node.test
    if not (isinstance(t, ast.Compare) and len(t.ops) == 1 and isinstance(t.ops[0], ast.Eq)):
        return node, False
    left = t.left
    if not (isinstance(left, ast.Call) and isinstance(left.func, ast.Name)
            and left.func.id == "repr" and len(left.args) == 1):
        return node, False
    comp = t.comparators[0]
    if not (isinstance(comp, ast.Constant) and isinstance(comp.value, str)):
        return node, False
    try:
        value_node: ast.expr = ast.parse(comp.value, mode="eval").body
    except SyntaxError:
        return node, False

    used_pytest = False
    if approx and "." in comp.value:          # contains a float -> tolerate rounding
        value_node = ast.Call(
            func=ast.Attribute(value=ast.Name(id="pytest", ctx=ast.Load()),
                               attr="approx", ctx=ast.Load()),
            args=[value_node], keywords=[])
        used_pytest = True

    new = ast.Assert(
        test=ast.Compare(left=left.args[0], ops=[ast.Eq()], comparators=[value_node]),
        msg=None)
    return ast.fix_missing_locations(new), used_pytest


# ── module-level cleanup ─────────────────────────────────────────────────────
def _is_syspath_insert(node: ast.stmt) -> bool:
    if not (isinstance(node, ast.Expr) and isinstance(node.value, ast.Call)):
        return False
    f = node.value.func
    return (isinstance(f, ast.Attribute) and isinstance(f.value, ast.Attribute)
            and isinstance(f.value.value, ast.Name) and f.value.value.id == "sys")


def transform_module(src: str, *, approx: bool = False) -> ast.Module:
    """Return a cleaned AST: header/sys bootstrap removed, repr-locks rewritten."""
    mod = ast.parse(src)
    used_pytest = False
    new_body: list[ast.stmt] = []
    for node in mod.body:
        # leading "Generated by ..." module docstring
        if (not new_body and isinstance(node, ast.Expr)
                and isinstance(node.value, ast.Constant) and isinstance(node.value.value, str)):
            continue
        if _is_syspath_insert(node):
            continue
        if isinstance(node, ast.Import):
            node.names = [a for a in node.names if a.name not in ("sys", "pytest")]
            if not node.names:
                continue
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            for i, stmt in enumerate(node.body):
                if isinstance(stmt, ast.Assert):
                    node.body[i], up = _rewrite_assert(stmt, approx=approx)
                    used_pytest = used_pytest or up
        new_body.append(node)

    if used_pytest:
        new_body.insert(0, ast.Import(names=[ast.alias(name="pytest")]))
    mod.body = new_body
    return ast.fix_missing_locations(mod)


def cleaned_source(src: str, *, approx: bool = False) -> str:
    return ast.unparse(transform_module(src, approx=approx)) + "\n"


# ── append-into-existing-suite ───────────────────────────────────────────────
def _render_import(module: str, names: set[str]) -> str:
    return f"from {module} import {', '.join(sorted(names))}"


def promote_into(draft_src: str, dest_path: Path, *, approx: bool = False) -> dict:
    """Append non-duplicate test functions from the draft into `dest_path`, merging imports.

    Existing content/formatting is preserved; only the touched import lines are rewritten
    and the new functions are appended. Returns a summary dict.
    """
    draft = transform_module(draft_src, approx=approx)
    draft_funcs = [n for n in draft.body if isinstance(n, ast.FunctionDef)]
    draft_imports = [n for n in draft.body if isinstance(n, ast.ImportFrom) and n.module]

    dest_text = dest_path.read_text(encoding="utf-8-sig")   # tolerate a BOM
    dest = ast.parse(dest_text)
    existing_funcs = {n.name for n in dest.body if isinstance(n, ast.FunctionDef)}
    new_funcs = [f for f in draft_funcs if f.name not in existing_funcs]
    skipped = [f.name for f in draft_funcs if f.name in existing_funcs]

    # what each module needs imported
    wanted: dict[str, set[str]] = {}
    for imp in draft_imports:
        wanted.setdefault(imp.module, set()).update(a.name for a in imp.names)

    dest_importfroms = {n.module: n for n in dest.body
                        if isinstance(n, ast.ImportFrom) and n.module}
    last_import_line = max(
        (n.end_lineno or n.lineno for n in dest.body
         if isinstance(n, (ast.Import, ast.ImportFrom))), default=0)

    replace: dict[int, str | None] = {}     # 1-based lineno -> new text (None = delete line)
    additions: list[str] = []
    merged_modules: list[str] = []
    for module, names in wanted.items():
        node = dest_importfroms.get(module)
        if node is None:
            additions.append(_render_import(module, names))
            continue
        merged = {a.name for a in node.names} | names
        if merged != {a.name for a in node.names}:
            merged_modules.append(module)
        replace[node.lineno] = _render_import(module, merged)
        for ln in range(node.lineno + 1, (node.end_lineno or node.lineno) + 1):
            replace[ln] = None              # collapse a multi-line import to one line

    # rebuild dest text with import edits + new-module imports
    out: list[str] = []
    for i, line in enumerate(dest_text.splitlines(), start=1):
        if i in replace:
            if replace[i] is not None:
                out.append(replace[i])      # type: ignore[arg-type]
        else:
            out.append(line)
        if i == last_import_line and additions:
            out.extend(additions)

    body = "\n".join(out).rstrip()
    if new_funcs:
        funcs_src = "\n\n\n".join(ast.unparse(f) for f in new_funcs)
        body = f"{body}\n\n\n{funcs_src}"
    dest_path.write_text(body + "\n", encoding="utf-8")

    return {
        "added": [f.name for f in new_funcs],
        "skipped_duplicates": skipped,
        "imports_merged": merged_modules,
        "imports_added": additions,
        "dest": str(dest_path),
    }
