"""`web` → Playwright adapter (M4).

introspect: load the page headless (Playwright/Chromium — bundled Node driver, no system Node) and
scan the DOM for interactive elements + stable selectors.
emit: render a SELF-CONTAINED Python-Playwright pytest function from a scenario's structured
`actions` (no pytest-playwright plugin needed — each test launches its own headless browser, so it
runs under the same runner as the python adapter).
typescript: also export an idiomatic Playwright **.spec.ts** as a portfolio artifact.

The portfolio half of the tool; same shared core, one new adapter file, zero core edits beyond the
generic `elements`/`actions` fields on the scenario contract.
"""
from __future__ import annotations

import re
from pathlib import Path

from scripts.core.models import TargetContract, TargetRef, TestScenario, UnitSpec

name = "web_playwright"
prompt_kind = "web"


# ── url / selector helpers ───────────────────────────────────────────────────
def _to_url(locator: str) -> str:
    if locator.startswith(("http://", "https://", "file://")):
        return locator
    p = Path(locator)
    return p.resolve().as_uri() if p.exists() else locator


def _slug(value: str) -> str:
    s = re.sub(r"\W+", "_", str(value)).strip("_")
    return s or "scenario"


_SCAN_JS = """() => {
  const sel = 'button, a[href], input, textarea, select, [data-testid], [role=button]';
  return Array.from(document.querySelectorAll(sel)).slice(0, 40).map(el => ({
    tag: el.tagName.toLowerCase(),
    type: el.getAttribute('type'),
    name: el.getAttribute('name'),
    id: el.id || null,
    testid: el.getAttribute('data-testid'),
    placeholder: el.getAttribute('placeholder'),
    text: (el.innerText || el.value || '').trim().slice(0, 40),
  }));
}"""


def _selector(e: dict) -> str:
    if e.get("id"):
        return f"#{e['id']}"
    if e.get("testid"):
        return f"[data-testid=\"{e['testid']}\"]"
    if e.get("name"):
        return f"[name=\"{e['name']}\"]"
    if e["tag"] in ("button", "a") and e.get("text"):
        return f"{e['tag']}:has-text(\"{e['text']}\")"
    return e["tag"]


# ── adapter surface ──────────────────────────────────────────────────────────
def introspect(ref: TargetRef) -> TargetContract:
    from playwright.sync_api import sync_playwright

    url = _to_url(ref.locator)
    elements: list[dict] = []
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()
        try:
            page.goto(url, wait_until="domcontentloaded")
            title = page.title()
            for e in page.evaluate(_SCAN_JS):
                elements.append({
                    "tag": e["tag"], "selector": _selector(e),
                    "text": e.get("text") or "", "type": e.get("type") or "",
                    "name": e.get("name") or "", "placeholder": e.get("placeholder") or "",
                })
        finally:
            browser.close()

    unit = UnitSpec(name=ref.selector or "page", kind="route",
                    signature=f"({url})", docstring=title, elements=elements)
    return TargetContract(ref=ref, module=url, units=[unit])


def describe_contract(contract: TargetContract) -> str:
    u = contract.units[0]
    lines = [f"Web page: {contract.module}", f"Title: {u.docstring or '(none)'}",
             f"Target route name (use as scenario.unit): {u.name}", "",
             "Interactive elements — use these EXACT selectors:"]
    for e in u.elements:
        hint = e.get("text") or e.get("placeholder") or e.get("name") or e.get("type") or ""
        lines.append(f"- {e['tag']} `{e['selector']}`" + (f"  — {hint}" if hint else ""))
    if not u.elements:
        lines.append("- (no interactive elements detected)")
    return "\n".join(lines)


def file_header(contract: TargetContract, scenarios=()) -> str:
    return (
        '"""Generated by AI Test Pilot (web_playwright) — REVIEW before promoting.\n'
        'Self-contained Python-Playwright tests; each launches its own headless Chromium.\n'
        '"""\n'
        "import re\n\n"
        "from playwright.sync_api import expect, sync_playwright\n\n"
        f"BASE_URL = {contract.module!r}\n"
    )


def _render_action(a) -> str:
    s = a.selector
    if a.action == "click":
        return f"_page.click({s!r})"
    if a.action == "fill":
        return f"_page.fill({s!r}, {a.value!r})"
    if a.action == "check":
        return f"_page.check({s!r})"
    if a.action == "select":
        return f"_page.select_option({s!r}, {a.value!r})"
    if a.action == "press":
        return f"_page.press({s!r}, {a.value!r})"
    if a.action == "expect_text":
        return f"expect(_page.locator({s!r})).to_contain_text({a.text!r})"
    if a.action == "expect_visible":
        return f"expect(_page.locator({s!r})).to_be_visible()"
    if a.action == "expect_hidden":
        return f"expect(_page.locator({s!r})).to_be_hidden()"
    if a.action == "expect_value":
        return f"expect(_page.locator({s!r})).to_have_value({a.value!r})"
    if a.action == "expect_url":
        return f"assert {a.value!r} in _page.url"
    return f"pass  # unknown action {a.action!r}"


def emit(scenario: TestScenario, contract: TargetContract) -> str:
    body = [f"def test_{_slug(scenario.id)}():",
            f'    """{scenario.title}',
            "",
            f"    Why: {scenario.rationale or '-'}",
            f"    Expected: {scenario.expected}",
            '    """',
            "    with sync_playwright() as _p:",
            "        _b = _p.chromium.launch()",
            "        _page = _b.new_page()",
            "        try:",
            "            _page.goto(BASE_URL)"]
    if scenario.actions:
        body += [f"            {_render_action(a)}" for a in scenario.actions]
    else:
        body.append('            import pytest; pytest.skip("scenario had no actions")')
    body += ["        finally:", "            _b.close()", ""]
    return "\n".join(body)


def typescript(scenario: TestScenario, contract: TargetContract) -> str:
    """Idiomatic Playwright TypeScript for the same scenario (published artifact, not run here)."""
    ts_map = {
        "click": lambda a: f"await page.click('{a.selector}');",
        "fill": lambda a: f"await page.fill('{a.selector}', '{a.value}');",
        "check": lambda a: f"await page.check('{a.selector}');",
        "select": lambda a: f"await page.selectOption('{a.selector}', '{a.value}');",
        "press": lambda a: f"await page.press('{a.selector}', '{a.value}');",
        "expect_text": lambda a: f"await expect(page.locator('{a.selector}')).toContainText('{a.text}');",
        "expect_visible": lambda a: f"await expect(page.locator('{a.selector}')).toBeVisible();",
        "expect_hidden": lambda a: f"await expect(page.locator('{a.selector}')).toBeHidden();",
        "expect_value": lambda a: f"await expect(page.locator('{a.selector}')).toHaveValue('{a.value}');",
        "expect_url": lambda a: f"await expect(page).toHaveURL(/{re.escape(a.value or '')}/);",
    }
    steps = "\n  ".join(ts_map.get(a.action, lambda a: "")(a) for a in scenario.actions)
    return (f"test('{scenario.title}', async ({{ page }}) => {{\n"
            f"  await page.goto(BASE_URL);\n  {steps}\n}});\n")


def test_function_name(scenario: TestScenario) -> str:
    return f"test_{_slug(scenario.id)}"


def runner_cmd(test_path: Path) -> list[str]:
    return ["pytest", "-q", "--no-header", str(test_path)]
